[build]
  command = "npm run build"         # Command to build the app
  publish = ".output/public"       # Location of static assets
  functions = ".netlify/functions-internal/server"  # Location of serverless functions

[build.environment]
  SERVER_PRESET = "netlify"        # Nitro preset for Netlify